site_name: SQLAlchemy Admin
site_description: Flexible admin dashboard for SQLAlchemy.

theme:
  name: 'material'
  palette:
      primary: white

repo_name: aminalaee/sqladmin
repo_url: https://github.com/aminalaee/sqladmin
edit_uri: ""

nav:
  - Introduction: 'index.md'

markdown_extensions:
  - markdown.extensions.codehilite:
      guess_lang: false
  - mkautodoc
